### ISSUE TITLE
how can i remap /os_cloud_node/lidar_packets into standard sensor_msgs/PointCloud2?

### ISSUE THREAD

**Issue by AcamelQ** [ntnu-arl/lidar_degeneracy_datasets#1]
thanks for your sharing. here is the issue, when i tried to test this package with my project, i encountered a problem to change the lidar topic  /os_cloud_node/lidar_packets into  sensor_msgs/PointCloud2. i already tried https://github.com/ouster-lidar/ouster-ros roslaunch ouster_ros replay.launch      \
    bag_file:=<path to rosbag file>     \
    metadata:=<json file name>  
    but it didn't successfully replay this bag.
    can you help me with this issue.
    best regards!

**Comment by nkhedekar** [comment]
Hi @AcamelQ , Please use the sensor_sync_replay branch of our fork of ouster-ros : https://github.com/ntnu-arl/ouster-ros/tree/dev/sensor_sync_replay
